#!/usr/bin/env bash
set -euo pipefail

source_dir=$(realpath .)

mkdir -p ./dist
docker build --build-arg BUILD_USER_ID=${UID} -t genie /home/fleorin/proj/genius-builder/
docker run --rm -it -v ${source_dir}:/source -v ${source_dir}/dist:/dist genie $@

