#!/usr/bin/env bash
set -euo pipefail

mkdir -p ./dist
SOURCE_DIR=$(pwd)
DIST_DIR="${SOURCE_DIR}/dist"

docker run --rm -it \
    -v "${SOURCE_DIR}:/source" \
    -v "${DIST_DIR}:/dist" \
    fleorin/genius-builder $@

