#!/usr/bin/env bash
set -euo pipefail

declare -a ANDROID_ABIs=(
    arm64-v8a
    armeabi-v7a
    x86_64
    x86
)

# ## Configure CMAKE
# ENV ANDROID_CMAKE_TOOLCHAIN="${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake" \
#     CMAKE_TOOLCHAIN_FILE="${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake" \
#     ANDROID_ABI="arm64-v8a" \
#     ANDROID_PLATFORM="android-21" \
#     ANDROID_STL="c++static" \
#     ANDROID_TOOLCHAIN="clang" \
#     ANDROID_ARM_MODE="arm" \
#     CC="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" \
#     CXX="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" \
#     PATH="${ANDROID_NDK_ROOT}:${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" 

build_android()
{
    rm -rf *
    platform=android
    abi=$1
    cmake -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake" \
        -DANDROID_PLATFORM="android-21" \
        -DANDROID_ABI=$abi \
        -DCMAKE_ANDROID_ARCH_ABI=$abi \
        -DCMAKE_CXX_COMPILER_ABI=$abi \
        -DANDROID_STL="c++_static" \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/dist/${platform}-${abi}" \
        -S /source
    cmake --build .
    cmake --install . --prefix "/dist/${platform}-${abi}"
    echo "-- ${platform}-${abi} is ready for distribution"
}

build_linux()
{
    rm -rf *
    platform=linux
    abi=x86_64
    cmake -S /source
    cmake --build .
    cmake --install . --prefix "/dist/${platform}-${abi}"
    echo "-- ${platform}-${abi} is ready for distribution"
}

main()
{
    case $1 in
        shell)
            bash
            ;;

        debug|release)
            export CMAKE_BUILD_TYPE=${1^}
            shift

            ## linux builds come in only one flavow
            build_linux

            ## android builds are for most common platforms
            for abi in "${ANDROID_ABIs[@]}"; do
                build_android $abi
            done
            ;;

        *)
            "$@"
            ;;
    esac
}

printf "\t..: Preparing $VERSION [$CONTEXT] :..\n"
main "$@"
