#!/usr/bin/env bash
set -euo pipefail

docker build --build-arg BUILD_USER_ID=${UID} -t fleorin/genius-builder /home/fleorin/proj/genius-builder/

USE_TAG=$(git describe --exact-match 2>/dev/null || echo "latest")
docker push fleorin/genius-builder:${USE_TAG}

