#!/usr/bin/env bash
set -euo pipefail

USE_TAG=$(git describe --exact-match 2>/dev/null || echo "latest")
docker build \
    --build-arg builder_uid=${UID} \
    --tag fleorin/genius-builder:${USE_TAG} \
    --tag fleorin/genius-builder:latest \
    .

